### ISSUE TITLE
Strings.po Italian

### ISSUE THREAD

**Issue by dga4130-renato** [HungerHa/libreelec_package_argonforty-device#4]
[strings.po.zip](https://github.com/HungerHa/libreelec_package_argonforty-device/files/15370755/strings.po.zip)

Italian translation

**Comment by dga4130-renato** [comment]
Will have to test this before release, just  to check formatted text lenght and real sense of the words. thanks

**Comment by HungerHa** [comment]
This is my first time dealing with translation files. But we should keep two things in mind:

- The msgid string should always be English and the translated string must be the msgstr.
- We should try to maintain the metadata in the header correctly regarding language, date and translator (you).

I would like it to be proofread by a native speaker. There is also an option for automatic translation into several languages.
https://kodi.wiki/view/Translating_add-ons#Workflows_and_scripts

**Comment by dga4130-renato** [comment]
[strings.po.zip](https://github.com/HungerHa/libreelec_package_argonforty-device/files/15377191/strings.po.zip)

corrected msgid and msgstr.

just in case you want to implement this. 
if you prefer other solutions welcome. quit easy for me anyway ...i'm english and live in italy, was a 2 minute shot !

**Comment by HungerHa** [comment]
Please can you translate these two lines too?

https://github.com/HungerHa/libreelec_package_argonforty-device/blob/da139a0cbce1be4f80a9506a0a32f063fe26fe93/source/addon.xml#L13-L14

Or check if Google translation is right:
```
<summary lang="it_IT">Configurazione del dispositivo ArgonForty</summary>
<description lang="it_IT">Installa servizi per gestire i dispositivi ArgonForty come pulsante di accensione e velocità della ventola. Ciò abiliterà anche I2C, ricevitore IR e UART.</description>

```

**Comment by dga4130-renato** [comment]
Sounds ok , google is a quit ok  translator . 
Sometimes makes a no sense but 99% 
Gives ok results. 
Most time the English to Italian gives s quit longer phrase and goes out of the lines that's why I said I need to check alignment and chance the way to say things in order to get a shorter one.

**Comment by dga4130-renato** [comment]
<summary lang="en_GB">ArgonForty Device Configuration</summary> 
 <description lang="en_GB">Install services to manage ArgonForty devices such as power button and fan speed. This will also enable I2C, IR receiver and UART.[CR][CR] * Disable then Enable Service for settings to take effect (or reboot)</description> 
 
 <summary lang="it_IT">Configurazione del dispositivo ArgonForty</summary> 
 <description lang="it_IT">Installa i servizi per gestire ArgonForty, come pulsante di accensione e velocità della ventola. Ciò abiliterà anche I2C, ricevitore IR e UART.[CR][CR] * Disabilita e abilita il servizio affinché le impostazioni abbiano effetto (o riavvia)</description>

**Comment by HungerHa** [comment]
Thank you for providing the translation file.

This time it wasn't a fail of Google that the second sentence was missing. I have truncated that part during preparation of the translation files, because I think the statement is wrong now. It's not needed anymore to Disable/Enable the service for settings to take effect. New values will adapted immediately, but it could take up to 30 seconds until the current running fan regulation cycle is finished if the new target fan speed is lower.

Reboot is needed only after the first installation to activate the modules for I2C, IR and the UART. But this is a one time use case and described in installation readme.

Maybe I will change the <description> again, because currently it feels incomplete to me.

**Comment by dga4130-renato** [comment]
Installed but, as I was imagining before, there's some fixes in translation to fix.
Will do this asap and upload a new .po

**Comment by HungerHa** [comment]
Is it possible to also add the remote control text to better match the current README file ?

> Installs services to manage ArgonForty devices such as power button, fan speed and Argon REMOTE. This will also enable I2C, IR receiver and UART.

**Comment by dga4130-renato** [comment]
[strings.po.zip](https://github.com/HungerHa/libreelec_package_argonforty-device/files/15408772/strings.po.zip)
new string.po
this is final translation. nothing to do with google translator. Perfect alignment and translation with more more technical sense

**Comment by dga4130-renato** [comment]
Installa i servizi per gestire ArgonForty : Pulsante di accensione, velocità  ventola e Argon REMOTE. 
Verranno abilitati  I2C,  IR e UART

**Comment by mcrae1** [comment]
Buenas quería saber como instalarlo y configurar en español.
