### ISSUE TITLE
Is this project a replacement for libreelec_argondevice_0.0.13.zip?

### ISSUE THREAD

**Issue by stevemesser** [HungerHa/libreelec_package_argonforty-device#8]
Is this project a replacement for libreelec_argondevice_0.0.13.zip?

**Comment by HungerHa** [comment]
Hi Steve,
this was already the project for the libreelec_argondevice_x.x.x.zip. Just the binary packages are now released here too https://github.com/HungerHa/libreelec_package_argonforty-device/releases. Version 1.1.1 is a successor to 0.0.13. For more information, see the [changelog.txt](https://github.com/HungerHa/libreelec_package_argonforty-device/blob/master/changelog.txt).
